### ISSUE TITLE
Pick and Add Command Issues

### ISSUE THREAD

**Issue by SeekSaveServe** [AY2223S1-CS2103-F14-1/tp#105]
Found some issues and bugs with the Pick command:

- [x] Tutorial number is case sensitive  (01A is correct but not 01a). This is strange since all our other parsers are case insensitive
- [ ] Cannot add lecture slot
- [ ] Adding invalid lab code is accepted
  1.     `add cs2030s s1 lab 01A` adds the module 
  2.      lab is not shown in the chosen lesson slot since it is invalid
  3.      Further attempts to add lab slots is not possible without removing the module despite no valid lab slot being selected
- [ ] Cannot add both lab and tutorial slots

**Comment by zupey** [comment]
Found some issues with the Add command:

- [ ] Adding gibberish to a valid add command works.
![image](https://user-images.githubusercontent.com/53803800/198359259-a38aac73-135b-401e-8e85-77c59f369e01.png)
