### ISSUE TITLE
[PE-D][Tester B] New example in command summary without explanation

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F14-1/tp#129]
The `ls` command part in command summary mentioned an example `ls MA --user`. It does not appear in the main part and there is no explanation for the additional `--user`. Readers may get confused about the meaning of it.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: WuHaohui1231/ped#2

**Comment by zupey** [comment]
Update UG to deprecate `--user`

**Comment by zupey** [comment]
Addressed in #166
