### ISSUE TITLE
[PE-D][Tester A] Inconsistent "invalid message"

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F14-1/tp#132]
When a module code with less than 4 numbers following the code is searched for with `view`, the message given is "Invalid module code: csxxx" while for a module code with more than 4 numbers, the message given is "csxxxxx not in NUS curriculum". I feel like these 2 cases should share the same message.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: WR3nd3/ped#4

**Comment by zupey** [comment]
Standardise error message to 'cs10000' invalid or not in current NUS curriculum
