### ISSUE TITLE
[PE-D][Tester A] Maximum height of view-module window

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103-F14-1/tp#139]
The maximum height of the view-module window is somewhat restrictive and can cause scrolling through potential classes to be frustrating.

![image.png](https://raw.githubusercontent.com/WR3nd3/ped/main/files/5332b4e0-b1d9-4d82-9f62-91bce74b99ae.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: WR3nd3/ped#6

**Comment by zupey** [comment]
Duplicate with #120
