### ISSUE TITLE
[PE-D][Tester A] Editing the JSON file: Renaming modulecode

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103-F14-1/tp#150]
You are able to rename modules in the JSON file.

![image.png](https://raw.githubusercontent.com/WR3nd3/ped/main/files/375d09b5-906d-4a63-914e-9eb5b53cb1c8.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: WR3nd3/ped#10

**Comment by zupey** [comment]
Addressed in #166
