### ISSUE TITLE
Improve `ls command`

### ISSUE THREAD

**Issue by SeekSaveServe** [AY2223S1-CS2103-F14-1/tp#67]
TODO:

- [ ] Improve test coverage
- [ ] Change FAULTY_FACULTY_CODE to a less hacky method
- [x] Add support for `--user` flag

**Comment by zupey** [comment]
@SeekSaveServe
# Bug
* Searching for `ST` yields results for `BST` and `FST`

**Comment by SeekSaveServe** [comment]
> @SeekSaveServe
> 
> # Bug
> * Searching for `ST` yields results for `BST` and `FST`
 
### Fixed with my latest PR :)
